# -*- coding: utf-8 -*-
"""
Created on Wed Aug  9 00:00:24 2023

@author: johna
"""

lookups = {
    'Gender' : 'Demographic',
    'Date of Birth' : 'VOID',
    'Ethnicity' : 'VOID', # not enough unique values (505 not hispanic)
    'Marital Status ' : 'Demographic',
    'Patient Information Comments' : 'VOID', # free text field
    'Completed By' : 'VOID', # This is just the name of who completed questionnaire
    'Family History of Cancer ' : "Family",
    'Number of Members with Cancer History ' : "Family",
    'Relative 1 Relationship ' : "VOID",
    'Relative 2 Relationship ' : "VOID",
    'Relative 3 Relationship ' : "VOID",
    'Relative 3 Other Cancer Type' : "VOID",
    'Relative 4 Relationship' : "VOID",
    'Relative 5 Relationship ' : "VOID",
    'Previous or Other Current Cancer Diagnosis' : "History",
    'Previous Chemotherapy' : "VOID", # only 21 yes
    'Previous Radiation' : "VOID", # only 29 yes
    'Previous Bone Marrow Transplant' : "VOID", # only 1 yes
    'Previous Cancer Surgery' : "VOID", # only 62 yes
    'Previous Cancer Surgery Date (s)' : "VOID",
    'Other Previous Surgery ' : "VOID",
    'Anticoagulants/antiplatelets ' : "Medications",
    'Nonsteroidal Anti-Inflammatory Drugs' : "Medications",
    'Anticonvulsants ' : "Medications",
    'Anti-anxiety/ Anti-depressants' : "Medications",
    'Narcotic Analgesics ' : "Medications",
    'Bisphosphanates' : "VOID", # only 3 yes
    'Vitamins, Minerals, and Herbal Supplements ' : "Medications",
    'Diabetes Controlled By' : "VOID",
    'Any other disease/condition not listed above? ' : "VOID",
    'Alcohol Consumption' : "Alcohol",
    'History of Alcohol Abuse ' : "Alcohol",
    'Current Smoking Status (within 1 month of treatment)' : "Tobacco",
    'Ever Smoked at least 100 Cigarettes in Entire Life ' : "Tobacco",
    'Age Started Smoking ' : "Tobacco",
    'Currently Smoke' : "Tobacco",
    'Number of days cig smoked (out of past 30 days) ' : "VOID",
    'Date quit smoking ' : "Tobacco",
    'How many years have you smoked ' : "Tobacco",
    'How many cigarettes smoked daily' :"Tobacco",
    'Pipe' : "VOID",
    'Cigars' : "VOID",
    'How much/many cigars per day' : "VOID",
    'How many years of cigar' : "VOID",
    'Chewing Tobacco' : "VOID",
    'Age began using chewing tobacco' : "VOID",
    'How many years of chewing tobacco' : "VOID",
    'Snuff' : "VOID",
    'Recreational Drugs' : "Drugs",
    'Age at Diagnosis ' : "Demographic",
    'Other Supraglottic Subsite' : "VOID",
    'Other Oropharynx Subsite ' : "VOID",
    'T Stage Clinical ' : "Cancer Stage",
    'N stage' : "Cancer Stage",
    'M stage' : "Cancer Stage",
    'Overall Clinical Stage' : "Cancer Stage",
    'Date of Overall Clinical Stage' : "VOID",
    'Biopsy Proven ' : "VOID", # only 2 yes
    'Pathological TNM Completed' : "VOID", # pathological stage not useful
    'Pathological T Stage' : "VOID",       # only 100ish total patients, and
    'Pathological N Stage' : "VOID",       # stages get subdivided, too small
    'Pathologic M Stage' : "VOID",
    'Overall Pathological Stage' : "VOID",
    'Lymph Nodes Examined' : "VOID",
    'Number of Lymph Nodes Examined' : "VOID",
    'Number Positive Lymph Nodes' : "VOID",
    'Lymph-vascular Invasion' : "VOID",
    'Perineural Invasion' : "VOID",
    'Positive Surgical Margins' : "VOID",
    'Extra-capsular Extension' : "VOID",
    'Pathologic Grading' : "VOID",
    'HPV status' : "Conditions",
    'Complete?.4' : "VOID",
    'Treatment Type ' : "Cancer General",
    'Other Induction Chemotherapy ' : "VOID",
    'Induction Chemotherapy Start Date' : "VOID",
    'Induction Chemotherapy End Date' : "VOID",
    'Induction Chemotherapy Duration' : "VOID",
    'Induction Chemotherapy Frequency ' : "VOID",
    'Other Primary Chemotherapy' : "VOID",
    'Primary Chemotherapy Start Date' : "VOID",
    'Primary Chemotherapy Duration' : "VOID",
    'Primary Chemotherapy End Date ' : "VOID",
    'Primary Chemotherapy Frequency' : "VOID", 
    'RT Start Date' : "RT",
    'RT Completion Date' : "POST RT",
    'RT Duration (days)' : "POST RT",
    'Radiation Delayed' : "VOID",
    'Type of Radiation' : "RT",
    'RT Total Dose to Primary Site (Gy)' : "RT",
    'RT Dose to Surrounding Tissues' : "RT",
    'Unlilateral or Bilateral ' : "RT",
    'Date of Surgery ' : "Surgery",
    'Nutrition Support' : "Nutrition", 
    'Date Feeding Tube in' : "Nutrition",
    'Date Feeding Tube Out ' : "VOID",
    'Duration of Feeding Tube (months)' : "Nutrition",
    'Duration of TPN (days)' : "VOID",
    'Was patient hospitalized during radiation therapy or within the 3 months following completion of therapy:' : "VOID",
    'Date admitted:' : "VOID",
    'Date discharged:' : "VOID",
    'Was patient hospitalized additional times during treatment or within 3 months of completing treatment?' : "VOID",
    'Date admitted:.1' : "VOID",
    'Date discharged:.1' : "VOID",
    'Was patient hospitalized a third time or more during this time frame?' : "VOID",
    'Complete?.5' : "VOID",
    'Radiation Start Date' : "RT",
    'Radiation Completion Date ' : "POST RT",
    'Pre treatment ECOG Score ' : "QOL Baseline",
    'Pre-treatment Karnofsky Performance Status ' : "QOL Baseline",
    'Date of Physical Measurements ' : "VOID",
    'Height (cm)' : "Physical",
    'Weight (kg)' : "Physical",
    'BMI' : "Physical",
    'Post Treatment Weight (kg)' : "POST Physical",
    'Post Treatment Weight Loss' : "POST Physical",
    'Treatment Weight Loss Percent' : "POST Physical",
    'Complete?.6' : "VOID",
    'Date of Pre Radiation Results' : "VOID",
    'Pre Radiation  WBC ' : "Host Factors",
    'Pre Radiation Hgb' : "Host Factors",
    'Pre Radiation Hct' : "Host Factors",
    'Pre Radiation Platelets' : "Host Factors",
    'Pre Radiation  RBC' : "Host Factors",
    'Pre Radiation MCV' : "Host Factors",
    'Pre Radiation MCH' : "Host Factors",
    'Pre Radiation MCHC' : "Host Factors",
    'Pre Radiation Neutrophil Percent (%)' : "Host Factors",
    'Pre Radiation Lymphocyte Percent (%)' : "Host Factors",
    'Pre Radiation Monocyte Percent (%)' : "Host Factors",
    'Pre Radiation Eosinophil Percent (%)' : "Host Factors",
    'Pre Radiation Basophil Percent (%)' : "Host Factors",
    'Pre Radiation Neutrophil Absolute/Manual Count ' : "Host Factors",
    'Pre Radiation Lymphocyte Absolute/Manual Count ' : "Host Factors",
    'Pre Radiation Monocyte Absolute/Manual Count ' : "Host Factors",
    'Pre Radiation Eosinophil Absolute/Manual Count ' : "Host Factors",
    'Pre Radiation Basophil Absolute/Manual Count ' : "Host Factors",
    'Pre Radiation Albumin' : "Host Factors",
    'Date of Post Treatment Results' : "POST Host Factors",
    'Post Radiation WBC ' : "POST Host Factors",
    'Post Radiation Hgb' : "POST Host Factors",
    'Post Radiation Hct' : "POST Host Factors",
    'Post Radiation Platelets' : "POST Host Factors",
    'Post Radiation RBC' : "POST Host Factors",
    'Post Radiation MCV' : "POST Host Factors",
    'Post Radiation MCH' : "POST Host Factors",
    'Post Radiation MCHC' : "POST Host Factors",
    'Post Radiation Neutrophil Percent (%)' : "POST Host Factors",
    'Post Radiation Lymphocyte Percent (%)' : "POST Host Factors",
    'Post Radiation Monocyte Percent(%)' : "POST Host Factors",
    'Post Radiation Eosinophil Percent (%)' : "POST Host Factors",
    'Post Radiation Basophil Percent (%)' : "POST Host Factors",
    'Post Radiation Neutrophil Absolute/Manual Count ' : "POST Host Factors",
    'Post Radiation Lymphocyte Absolute/Manual Count ' : "POST Host Factors",
    'Post Radiation Monocyte Absolute/Manual Count ' : "POST Host Factors",
    'Post Radiation Eosinophil Absolute/Manual Count ' : "POST Host Factors",
    'Post Radiation Basophil Absolute/Manual Count ' : "POST Host Factors",
    'Post Radiation Albumin' : "POST Host Factors",
    'Complete?.7' : "VOID",
    'Response to Treatment ' : "Response",
    'Date Response to Treatment Recorded' : "VOID",
    'Pre-treatment PET scan date:' : "VOID",
    'Post-treatment PET scan date:' : "POST PET",
    'Post-treatment PET scan radiologist read:' : "POST PET",
    'Course of action following post-treatment PET scan:' : "POST PET",
    'Other:.3' : "VOID",
    'Was repeat PET scan due to previous PET scan findings?' : "VOID",
    'Date of repeat PET scan:' : "VOID",
    'Repeat PET scan radiologist read:' : "VOID",
    'Pathology results of biopsy or surgery:' : "VOID",
    'Next course of action:' : "VOID",
    'Date of third PET scan:' : "VOID",
    'Third PET scan radiologist read:' : "VOID",
    'Pathology results of biopsy or surgery:.1' : "VOID",
    'Next course of action:.1' : "VOID",
    'Complete?.8' : "VOID",
    'Local Failure' : "VOID", # only 31 yes
    'Date of Local Failure' : "VOID",
    'Regional Failure' : "VOID", # only 31 yes
    'Date of Regional Failure' : "VOID",
    'Distant Failure' : "VOID", # only 48 yes
    'Date of Distant Failure ' : "VOID",
    'Second Primary in HN within first 5 years' : "VOID",
    'Date Second Primary in first 5 years' : "VOID",
    'Other Second Cancer Since Initial Diagnosis or Treatment ' : "VOID",
    'New Comorbidity Since Initial Diagnosis or Treatment  ' : "VOID",
    'Date of Last Follow Up' : "Follow Up",
    'Smoking status at last follow up' : "Follow Up",
    'Current Status' : "Follow Up",
    'Disease Status' : "Follow Up",
    'Date of Death' : "Follow Up",
    'Cause of Death' : "Follow Up",
    'Complete?.9' : "VOID",
    'Surgical Complications' : "VOID",
    'How Many?' : "VOID",
    'Category of Complication 1' : "VOID",
    'Complete?.10' : "VOID",
    'Race' : "Demographic",
    'MD Referred by?' : "VOID",
    'Relative 1 Cancer Type' : "VOID",
    'Relative 2 Cancer Type' : "VOID",
    'Relative 3 Cancer Type' : "VOID",
    'Relative 4 Cancer Type' : "VOID",
    'Relative 5 Cancer Type' : "VOID",
    'Type of Cancer' : "VOID", # not useful info, only secondary cancers
    'Allergies or Adverse reactions to:' : "Conditions",
    'Respiratory System' : "Conditions",
    'Nervous System' : "Conditions",
    'Immune System' : "Conditions",
    'Urinary System' : "Conditions",
    'Skeletal System' : "Conditions",
    'Endocrine Problems' : "Conditions",
    'Cardiovascular System' : "Conditions",
    'Digestive System' : "Conditions",
    'Type' : "VOID", # 524 SCC
    'Disease Site' : "Cancer General",
    'Subsite' : "Cancer General",
    'Supraglottic Subsite' : "VOID",
    'Oropharynx Subsite' : "Cancer General",
    'Induction Chemotherapy Type' : "VOID",
    'Primary Chemotherapy Type' : "Chemo",
    'Surgery Type' : "Surgery",
    'Type of Nutrition Support' : "Nutrition",
    'Feeding Tube Type' : "Nutrition",
    'Reason for admission:' : "VOID",
    'Site of equivocal or persistent findings:' : "VOID",
    'What was biopsy or surgery done for?' : "VOID"
    }

categories = list(set(lookups.values()))

groups = {k:[] for k in categories}
for k,v in lookups.items():
    groups[v].append(k)
